name: 'Telegram joke'
description: 'Send random joke to telegram'
author: 'Grigoryan-not-available'

inputs:
  chat_id:
    description: "Telegram bot chat id"
    required: true
  token:
    description: "Telegram bot token"
    required: true

outputs:
  joke:
    description: 'Random joke'

runs:
  using: node20
  main: dist/index.js
